# Generated by Django 3.1.13 on 2021-07-21 18:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleposition',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32140),
        ),
    ]
